
services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    restart: always
    networks:
      - diamond-bridge
    depends_on:
      - django
    volumes:
      - static_volume:/app/backend/staticfiles

  django:
    build:
      context: .
    container_name: django-cont
    env_file:
      - .env
    restart: always
    networks:
      - diamond-bridge
    depends_on:
      - mysql
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - static_volume:/app/backend/staticfiles

  mysql:
    image: mysql:8
    container_name: mysql-cont
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    networks:
      - diamond-bridge
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  diamond-bridge:

volumes:
  mysql_data:
  static_volume:
